# ~/.config/starship.toml
# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 30000

# Use custom format
format = """
$username\
$directory\
$git_branch\
$character"""

# Disable the blank line at the start of the prompt
add_newline = false

[git_status]
disabled = true
